### ISSUE TITLE
periodic-table-cli on Ubuntu Server

### ISSUE THREAD

**Issue by rsauve** [spirometaxas/periodic-table-cli#6]
I usually find some interesting stuff for the linux terminal reading the Linux Format magazine. FXF316 July 2024 edition article "Learn the periodic table" is all about periodic-table-cli.

I installed periodic-table-cli on my Mint Linux VM using: pip install periodic-table-cli
It works great!

However, when I tried to install periodic-table-cli (same procedure as above) on my Ubuntu server via ssh and run periodic-table-cli I get:
:~$ periodic-table-cli
Traceback (most recent call last):
  File "/home/robert/.local/bin/periodic-table-cli", line 8, in <module>
    sys.exit(main())
  File "/home/robert/.local/lib/python3.8/site-packages/periodic_table_cli/cli.py", line 226, in main
    _wrapper(app.start)
  File "/home/robert/.local/lib/python3.8/site-packages/periodic_table_cli/cli.py", line 183, in _wrapper
    curses.wrapper(func)
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/robert/.local/lib/python3.8/site-packages/periodic_table_cli/app.py", line 59, in start
    Colors.init_colors()
  File "/home/robert/.local/lib/python3.8/site-packages/periodic_table_cli/colors.py", line 74, in init_colors
    curses.init_pair(color_pair_id, fg_color.FG, Colors.BLACK.BG)
_curses.error: init_pair() returned ERR

Here is some information about my server:
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

OS: Ubuntu 20.04.6 LTS x86_64
Kernel: 5.4.0-186-generic
Uptime: 2 days, 15 hours, 39 mins
Packages: 1705 (dpkg)
Shell: bash 5.0.17
Terminal: /dev/pts/0
CPU: Intel Pentium N3700 (4) @ 2.400GHz
GPU: Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx
Memory: 971MiB / 7429MiB

Is it possible to get periodic-table-cli to run under Ubuntu Server via ssh?

**Comment by spirometaxas** [comment]
Thank you for installing periodic-table-cli and for providing the detailed information!  I found and patched a few issues that result in that error when connecting via ssh.  I have pushed the changes to the latest release (Python v2.1.3): https://github.com/spirometaxas/periodic-table-cli-py/releases/tag/v2.1.3

I tested using Ubuntu Server 24.04 and connected via ssh using Putty and Ubuntu terminal. Let me know if you are still seeing the issue. Thanks!

**Comment by rsauve** [comment]
ssh'ed into my ubuntu server and upgraded periodic-table-cli:

     ~$ pip install periodic-table-cli --upgrade
     ~$ periodic-table-cli --version
            v2.1.3 (Python)
     ~$ periodic-table-cli
<img width="1521" height="849" alt="Image" src="https://github.com/user-attachments/assets/977ecf97-1363-4ca9-baad-971eeeefd10b" />




Working!


Thank you for your help.
